version: '1.0'

services:
  mongo:
    image: mongo
    ports:
      - "3202:27017"
    environment:
      MONGO_INITDB_DATABASE: SigmaBot
    volumes:
      - /db-data/mongo/:/data/db

  sigma-bot:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: sigma_bot
    restart: always
    env_file:
      - ./.env